config/routes.rb
Rails.application.routes.draw do
    # Set the new view of the sessions controller as the root location
    root 'sessions#new'

    # Handle callbacks from OmniAuth by passing information to the create view
    match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
    match '/auth/failure', to: 'sessions#failure', via: [:get, :post]

    # Handle logout by destroying the current session
    match '/logout', to: 'sessions#destroy', :as => 'logout', via: [:get, :post]

    # Add views to Rails' routes
    get 'sessions/index'
    get 'sessions/create'

    # Set identities and wagers as resources to streamline routing
    resources :identities
    resources :wagers
end

app/models/wager.rb
class Wager < ActiveRecord::Base
    # No extra information necessary
end

app/controllers/wagers_controller.rb
class WagersController < ApplicationController
    # Method ot calculate time left
    def time_left(seconds)
        days = (seconds / 1.day).floor
        seconds -= days.days
        hours = (seconds / 1.hour).floor
        seconds -= hours.hours
        minutes = (seconds / 1.minute).floor
        seconds -= minutes.minutes
        { days: days, hours: hours, minutes: minutes, seconds: seconds }
    end

    # Method to gather information about current wagers 
    def index
        @wagers = Wager.where(:challenger => current_user.name)
        @wagers += Wager.where(:acceptor => current_user.name)
        @wagers.each do |wager|
            timeleft = self.time_left(Time.parse(wager.duration.to_s) - Time.parse(Time.now.to_s))
            wager.timeleft = timeleft[:days].to_s + " days, " +
                             timeleft[:hours].to_s + " hours, " +
                             timeleft[:minutes].to_s + " minutes, " +
                             timeleft[:seconds].to_s + " seconds left"
        end
    end

    # Helper method for create (is necessary to generate a form
    # to create a new wager.
    def new
        @wager = Wager.new
    end

    # Method to create a wager and then redirect the user to the
    # wager index.
    def create
        @wager = Wager.new(wager_params)
        @wager.challenger = current_user.name
        @wager.temp = rand(50)
        @wager.save

        redirect_to action: 'index'
    end

    # Method to access information from RunKeeper and display it for one
    # particular wager.
    def show
        require 'net/http'
        require 'uri'
        require 'json'

        # Determine type of activity (currently limited to 3 for beta purposes)
        @wager = Wager.find(params[:id])
        if @wager.activity == "Running"
            type = "Running"
        elsif @wager.activity == "Cycling"
            type = "Cycling"
        else
            type = "Swimming"
        end

        # Send an HTTP GET request to the server and receive the requested data
        uri = URI.parse("https://api.runkeeper.com/fitnessActivities/")

        # Do loop to handle HTTPS communication. Also, limit the scope of the requested data 
        Net::HTTP.start(uri.host, uri.port, :use_ssl => true, uri.scheme => 'https') do |http|
            request = Net::HTTP::Get.new(uri.request_uri)
            request["Authorization"] = session[:access_token]
            request["Accept"] = "application/vnd.com.runkeeper.User+json"
            params = {"noEarlierThan" => @wager.created_at.strftime("%Y%m%d"), "noLaterThan" => @wager.duration.strftime("%Y%m%d"),
                      "type" => type}
            uri.query = URI.encode_www_form(params)

            http = Net::HTTP.new(uri.host, uri.port)
            response = http.request(request)
        end

        @total_distance = response['total_distance']
    end

    def destroy
        @wager = Wager.find(params[:id])
        @wager.destroy

        redirect_to wagers_path
    end

    private
        # Private helper method to handle Rails 4's implementation of strong parameters
        def wager_params
            accessible = [:challenger, :acceptor, :amount, :activity, :duration, :created_at, :updated_at]
            params.require(:wager).permit(accessible)
        end
end

app/helpers/wagers_helper.rb
module WagersHelper
end

app/views/wagers/index.html.erb
<!-- local style to turn buttons into links -->
<style>
    tr:hover :not(th) {
        color:blue;
        background-color:gray;
    }
</style>

<div class="container">
    <div class="jumbotron">
        <!-- Begin table of wagers (competitions) -->
        <table class="table">
            <h2 style="text-align:center;">Current Competitions</h2>
            <thead>
                <th>Opponent</th>
                <th>Activity</th>
                <th>Amount</th>
                <th>Time Left</th>
            </thead>
            <tbody>
                <% @wagers.each do |wager| %>
                    <tr onclick="document.location = '/wagers/<%= wager.id %>';">
                        <% if current_user.name == wager.challenger %>
                            <td><%= wager.acceptor %></td>
                        <% else %>
                            <td><%= wager.challenger %></td>
                        <% end %>
                        <td><%= wager.activity %></td>
                        <td><%= wager.amount %></td>
                        <td><%= wager.timeleft %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
        <!-- end table -->

        <br />
        <%= link_to "Start a competition now!", new_wager_path %>
    </div>
</div>

app/views/wagers/new.html.erb
<div class="container">
    <div class="jumbotron">
        <!-- Begin form to generate new wagers -->
        <%= form_for(@wager, :html => {:class => 'form-horizontal'}) do |f| %>
            <% if @wager.errors.any? %>
                <div id="error_explanation" class="help-block">
                    <h2>
                        <%= pluralize(@wager.error.count, 'error') %> prohibited this wager from being saved.
                    </h2>

                    <ul>
                        <%= @wager.error.full_messages.each do |msg| %>
                            <li><%= msg %></li>
                        <% end %>
                    </ul>
                </div>
            <% end %>

            <div class="form-group">
                <%= f.label :acceptor, "Opponent" %>
                <%= f.select(:acceptor, options_for_select(current_user.friends.collect { |c| [c, c] }), {}, {class: 'form-control'}) %>
            </div>

            <div class="form-group">
                <%= f.label :amount %>
                <%= f.select(:amount, options_for_select([["$0", 0.00], ["$1", 1.00], ["$5", 5.00], ["$10", 10.00]]), {}, {class: 'form-control'}) %>
            </div>

            <div class="form-group">
                <%= f.label :activity %>
                <%= f.select(:activity, options_for_select([["Running", "Running"], ["Cycling", "Cycling"], ["Swimming", "Swimming"]]), {}, {class: 'form-control'}) %>
            </div>

            <div class="form-group">
                <%= f.label :duration, "End of Competition" %>
                <%= f.datetime_select(:duration) %>
            </div>

            <div class="form-group">
                <%= f.submit 'Submit', :class => 'btn btn-default' %>
            </div>
        <% end %>
        <!-- end form -->
    </div>
</div>

app/views/wagers/show.html.erb
<div class="container">
    <!-- Displays current user progress -->
    <h2>Competition Progress: <%= @wager.activity %></h2>
    <ul>
        <li>Your Progress: <%= @total_distance || @wager.temp || 0 %></li>
        <li>Your Opponent's Progress: <%= @total_distance || @wager.temp+10 || 0 %></li>
    </ul>

    <%= link_to "End Competition", wager_path(@wager), method: :delete, data: { confirm: "Are you sure?" } %>
</div>